version: '3'
services:
    nginx:
        volumes:
            - ./web:/var/www/app/web
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        image: php:7.2-fpm
        volumes:
            - ./:/var/www/app
        networks:
            - app_network